name: Linux

on:
  push:
    branches: [main, '0.*']
  pull_request:
    branches: [main, '0.*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libboost-system-dev libboost-program-options-dev libsqlite3-dev cmake

      - name: Build
        run: cmake . && make -j$(nproc)

      - name: Test
        run: make test ARGS="--output-on-failure"
