name: macOS

on:
  push:
    branches: [main, '0.*']
  pull_request:
    branches: [main, '0.*']

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install boost cmake sqlite

      - name: Build
        run: cmake . && make -j$(sysctl -n hw.ncpu)

      - name: Test
        run: make test ARGS="--output-on-failure"
